### ISSUE TITLE
Error when searching AND question on search results

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/central#20] opened 2024-09-30 13:42 UTC
Hi, 
This is Jeff B with OIAA. 
A meeting named "Daily Reflections" with the listing URL   https://aa-intergroup.org/meetings/daily-reflections

When I enter "daily-reflections" in the search, I get all the meetings with those words in it. Fair enough.
When  I enter "daily reflections", I get even more results. A lot of them without either of these words in the search. 
Is there a way of pulling only this meeting up without searching through them all if I don't have the record number?

Also, when performing the first search, if I click on "Load 25 more", I get this error even after reloading the previous page. 

Error
Route "routes/search" does not have an action, but you are trying to submit to it. To fix this, please add an `action` function to the route

Error: Route "routes/search" does not have an action, but you are trying to submit to it. To fix this, please add an `action` function to the route
    at https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:30:1320
    at qe (https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:32267)
    at Vo (https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:20413)
    at Pe (https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:19806)
    at Object.Tr [as navigate] (https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:18819)
    at https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:55827
    at O.createElement.fe.onSubmit (https://central.aa-intergroup.org/build/_shared/chunk-DGWG5CW7.js:1:60647)
    at Object.wc (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:5:9855)
    at Sc (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:5:10009)
    at Ec (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:5:10066)

User error? Any suggestions? thank you, Jeff B

**Comment by joshreisner** [comment] 2024-09-30 14:45
hi @twn2twn my bad the "Load 25 More" broke because of the work i did for you last week on #11 - it should be fixed now

regarding search results, looks like fields that are included in the search are meeting name, website, notes, and group name, recordId, and notes

so the "Friends in Recovery" meetings come up, for example, because "daily reflections" is in the group notes. should we adjust that, maybe take group notes out of the search?

on the front end it looks like it's only searching on meeting name, perhaps it would be good to remove meeting notes as well?

<img width="1111" alt="Screenshot 2024-09-30 at 7 43 33 AM" src="https://github.com/user-attachments/assets/b33272a0-d156-4234-93ea-c7227ff0ef80">

**Comment by twn2twn** [comment] 2024-09-30 15:51
Hi Josh, 
Thank you for all this. I'm asking now to see what they'd like to do, if anything. thx Jeff B

**Comment by twn2twn** [comment] 2024-09-30 18:36
Hi Josh, 
I now get this error about 6 pages into the search. 
Error
T is not iterable

TypeError: T is not iterable
    at https://central.aa-intergroup.org/build/routes/search-G4SX6KZ3.js:1:1586
    at Array.map (<anonymous>)
    at b (https://central.aa-intergroup.org/build/routes/search-G4SX6KZ3.js:1:1418)
    at mu (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:6:19484)
    at Pi (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:3153)
    at Xa (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:44792)
    at $a (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:39724)
    at Jf (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:39655)
    at br (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:39515)
    at Ui (https://central.aa-intergroup.org/build/entry.client-CX7Q62IU.js:8:35905)

**Comment by joshreisner** [comment] 2024-09-30 22:07
could you provide steps to reproduce? i searched "daily reflections" and then clicked Load 25 More approximately 20 times but didn't encounter an error

**Comment by twn2twn** [comment] 2024-10-01 16:06
Seems to be fine. In fairness, it was erroring a bit yesterday. Seems good to go. thank you! I'll get back here when we figure if there's a change needed to the scope of the search. thanks!

**Comment by joshreisner** [comment] 2024-10-05 03:00
going to close for now but lmk if we should change the search

**Closed by joshreisner** 2024-10-05 03:00 UTC
