### ISSUE TITLE
Central displaying group 3 x

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/central#19] opened 2024-09-26 19:48 UTC
I'm with OIAA. 
If you get into Central, Groups, and search for "NZ Daily Online into the World of the Spirit"

I get 21 meetings with the same OIMN 506. BUT when it lists them, I only see 7 at a time. Some have the public email, some have descriptions I moved around to see if it effected them all. 
Also, Sunday, while being listed in the same time zone, is +1 hr. 
Please let me know if you need more info. thank you, Jeff B

**Comment by joshreisner** [comment] 2024-09-26 21:00
hey @twn2twn - regarding the time zone, i think new zealand goes into daylight saving time this sunday, i'm guessing that's why it's showing that way

regarding the apparent duplicates - it looks like this might be entered 4x actually - i found four different groups that each have seven meetings 

https://central.aa-intergroup.org/groups/648cc4b2c8f6636525131a57
https://central.aa-intergroup.org/groups/6469aefe8035c9efcb069d3f
https://central.aa-intergroup.org/groups/646a516731f35be3d10eadf2
https://central.aa-intergroup.org/groups/648e50e5b291ed6c5135f0a2

i just used the search though, which i dont fully trust (#11) if someone has prod db access could you do a search for groups with recordId = 506? @mattbylett or @tim-rohrer ?

**Comment by mattbylett** [comment] 2024-09-26 23:08
Hi guys

I will check that query later on in the prod db - just got a bit on right
now

I can confirm though that NZ is going into Daylight savings this coming
weekend

Many thanks - more in a bit

Matt

**Comment by joshreisner** [comment] 2024-09-27 05:26
thanks @mattbylett ! i found the credentials

looks like what's happening is we actually have two searches: - there is a first pass to see if there's an exact match on the meeting name, and then, if that doesn't return results, a second pass where we do a full text search on groups and meetings

i think this first pass is not intuitive, so i've removed it. now it does the full text search only

additionally central is designed to support multiple accounts, so that the same server could handle multiple intergroups. i'm not sure why, but it looks like the OIAA prod database actually has meetings belonging to four accounts. i'm guessing someone might have deleted the three invalid account records, but left all the groups and meetings belonging to the old accounts in there. these should be cleaned up.

but this explains why we were seeing extra meetings - there was a bug in the first pass search where it was showing results from all accounts. removing it has fixed both problems 

going to close this because i think it's resolved now ;)

**Closed by joshreisner** 2024-09-27 05:26 UTC
